<?php
/* BPMS-1224 Переделка draftManager в caseManager */
G::LoadClass("plugin");

class caseManagerPlugin extends PMPlugin
{
  
  public function caseManagerPlugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "caseManager Plugin";
    $this->sDescription  = "Autogenerated plugin for class caseManager";
    $this->sPluginFolder = "caseManager";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 1;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = null; //set to null to allow plugin to be used in all workspaces
	//To limit the plugin to certain workspaces, list the workspace names separated by semicolons
    //$this->aWorkspaces = array("workflow");
    
    return $res;
  }

  public function setup()
  {
	//"processmaker" - верхнее меню
	$this->registerMenu("processmaker", "menuCaseManager.php");
	//"cases" - боковое меню, раздел заявки
	$this->registerMenu("cases", "menuCasesCaseManager.php");
	//redirect users with that role to a specified page after logging into ProcessMaker
	//$this->redirectLogin("PM_CASEMANAGER", "users/users_List");
  }

  public function install()
  {
    /* Не будем добавлять пока Роль PM_CASEMANAGER
	$RBAC = RBAC::getSingleton() ;
    $RBAC->initRBAC();
    $RBAC->createPermision("PM_CASEMANAGER");
	*/
  }
  
  public function enable()
  {
    
  }

  public function disable()
  {
    
  }
  
}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("caseManager", __FILE__);
